// ─────────────────────────────────────────────────────────────
// Parser for runs/<SONG>/.sections.json -- the file the SONG view
// timeline renders. Reads the existing flat-list schema produced
// by tools/songrun.py and turns it into the three static groups
// (Ambients / Leads / Beats) the UI shows, each with its orbit
// lanes (a1.. / b1.. / l1..) and every section placed by start
// time with a dwell-derived duration.
//
// Existing schema (one section per Tidal `do` block):
//   {
//     "song": "/abs/path.tidal",
//     "floor_synths": 90,
//     "sections": [
//       { "label": ":ECDYSIS", "dwell": null, "source": "do\n  l6 $ ...",
//         "line": 2, "at": 1787477101.0755892 },
//       ...
//     ]
//   }
//
//   - `at`      : wall-clock epoch seconds when the section fired.
//   - `dwell`   : null most of the time; when set, how many seconds
//                 the section stays before the next one. When null,
//                 duration is derived from the gap to the next
//                 section's `at` (the profiler's sampling cadence),
//                 with a fallback for the last section.
//   - `source`  : the `do` block body; scanned for `<orbit> $`
//                 statements to route the section onto the right
//                 track lane (l6, b1, a2, ...).
//
// The file lives at runs/<SONG>/.sections.json -- a hidden file
// inside each song folder. Not every folder has one: it is created
// when the bench runs (tools/songrun.py writes it). A missing file
// parses to an empty timeline, not an error, so the dropdown can
// list every song folder without choking on the ones not benched.
//
// When tools/songrun.py is re-implemented in Rust, the schema will
// adapt to the UI -- a nested groups/tracks/sections shape -- and
// this parser will thin to a direct load. The orbit-routing and
// dwell-derivation below exist only to bridge the two shapes today.
// ─────────────────────────────────────────────────────────────

use std::path::{Path, PathBuf};

use slint::{ModelRc, SharedString, VecModel};

// GroupData / TrackData / SectionData and the AppWindow type are
// generated by `slint::include_modules!()` in main.rs, which re-
// exports them at the crate root. We reference them through `crate::`
// rather than re-running the macro here -- a second include would
// generate a distinct module with identically-named but separate
// types, and the model we build would not match the one AppWindow
// expects.
use crate::{GroupData, SectionData, TrackData};

// Song runs live here, one folder per song. Matches the layout the
// bench writes (tools/songrun.py --out runs/<song>) and that the
// SONG view dropdown enumerates. Absolute so it works regardless of
// the app's cwd, mirroring RECORDINGS_DIR in recordings.rs.
pub const RUNS_DIR: &str = "/home/endo/Studio/Hub/runs";

// Static group definition: display name + orbit prefix. The order
// here is the order the groups appear on the timeline; it matches
// labels::MUTE_GROUP_NAMES and the hardcoded mock in ui/timeline.slint
// (BEATS, LEADS, AMBIENTS).
//
// Group accent colors are assigned by index on the Slint side
// (Theme.group-beats / -leads / -ambients), so no color crosses
// into Rust -- same convention as mute_model() in main.rs.
const GROUPS: [(&str, char); 3] = [
    ("BEATS", 'b'),
    ("LEADS", 'l'),
    ("AMBIENTS", 'a'),
];

// Highest orbit index per group we will materialize as a lane. The
// rig runs 6 per group today (ORBITS_PER_GROUP in main.rs), and the
// parser only ever emits a lane when at least one section routes to
// it, so this is just a cap on the lane numbering, not a fixed grid.
const MAX_ORBITS_PER_GROUP: usize = 6;

// Fallback duration for the last section (and any single-section
// song), where there is no "next `at`" to subtract from. The
// profiler samples every 5s, so 5s is the natural floor; a section
// that closes the song rarely has a measured tail, so give it room
// to be visible rather than a one-pixel sliver.
const DEFAULT_SECTION_DURATION: f32 = 30.0;

// ── raw JSON shapes (serdeless) ──────────────────────────────
// We parse by hand rather than pulling serde as a dependency: the
// schema is fixed, small, and the rest of the crate stays dep-light
// (only slint + tokio). A tolerant, line-oriented reader also fails
// softly on a half-written file -- a bench run can leave a truncated
// .sections.json behind, and that should read as "no sections yet",
// not a crash.

#[derive(Debug, Clone)]
struct RawSection {
    label: Option<String>,
    dwell: Option<f32>,
    source: Option<String>,
    at: Option<f64>,
}

#[derive(Debug, Default)]
struct RawFile {
    song: Option<String>,
    sections: Vec<RawSection>,
}

// ── the parsed result ────────────────────────────────────────

/// A section placed on one track lane. `start` is seconds from the
/// song's first section; `duration` is dwell (or the gap to the next
/// section); `label` is the section name shown on the block.
#[derive(Debug, Clone, PartialEq)]
pub struct ParsedSection {
    pub label: String,
    pub start: f32,
    pub duration: f32,
}

/// One orbit lane (a1, b3, l6, ...). `orbit` is the slug ("a1");
/// `sections` are the sections routed onto this lane, in time order.
#[derive(Debug, Clone, PartialEq)]
pub struct ParsedTrack {
    pub orbit: String,
    pub sections: Vec<ParsedSection>,
}

/// One static group: "BEATS" / "LEADS" / "AMBIENTS".
#[derive(Debug, Clone, PartialEq)]
pub struct ParsedGroup {
    pub name: String,
    pub tracks: Vec<ParsedTrack>,
}

/// The fully parsed song timeline, plus metadata for the UI header.
#[derive(Debug, Clone, PartialEq)]
pub struct ParsedSong {
    pub song: String,
    pub groups: Vec<ParsedGroup>,
    pub duration: f32,
}

impl ParsedSong {
    pub fn is_empty(&self) -> bool {
        self.groups.iter().all(|g| g.tracks.is_empty())
    }
}

// ── orbit routing ────────────────────────────────────────────
// A section routes onto a lane when its `source` contains a
// `<orbit> $` statement at statement-start indentation -- i.e. the
// orbit name followed by `$` is the pattern-binding operator Tidal
// uses. Mirrors ORBIT_STMT in tools/orbitreport.py:
//   r"^\s+(?P<orbit>(?:[ab]\d+|l\d+))\s*\$"
// We accept a / b / l prefixes (the static groups) and reject
// anything else, so a stray `$` inside an expression never invents
// a lane.
fn orbits_in_source(source: &str) -> Vec<String> {
    let mut out = Vec::new();
    for line in source.lines() {
        let trimmed = line.trim_start();
        // Must start with a letter we recognize, then digits, then `$`.
        let Some(rest) = trimmed.strip_prefix(|c: char| matches!(c, 'a' | 'b' | 'l')) else {
            continue;
        };
        let digits_end = rest
            .find(|c: char| !c.is_ascii_digit())
            .unwrap_or(rest.len());
        if digits_end == 0 {
            continue;
        }
        let after = &rest[digits_end..];
        // Tolerate spaces between the orbit name and `$`.
        let after_trim = after.trim_start();
        if after_trim.starts_with('$') {
            let orbit = format!("{}{}", &trimmed[..1], &rest[..digits_end]);
            if !out.contains(&orbit) {
                out.push(orbit);
            }
        }
    }
    out
}

// ── JSON tokenization (minimal, tolerant) ────────────────────
// We do not need a full JSON parser: the file is an object with
// known keys. A streaming scan for string scalars and numbers keyed
// by the labels above is enough, and survives trailing truncation.

struct JsonScan<'a> {
    bytes: &'a [u8],
    pos: usize,
}

impl<'a> JsonScan<'a> {
    fn new(s: &'a str) -> Self {
        Self {
            bytes: s.as_bytes(),
            pos: 0,
        }
    }

    fn peek(&self) -> Option<u8> {
        self.bytes.get(self.pos).copied()
    }

    fn bump(&mut self) -> Option<u8> {
        let b = self.peek()?;
        self.pos += 1;
        Some(b)
    }

    fn skip_ws(&mut self) {
        while let Some(b) = self.peek() {
            if matches!(b, b' ' | b'\t' | b'\n' | b'\r') {
                self.pos += 1;
            } else {
                break;
            }
        }
    }

    // Read a JSON string literal (without the surrounding quotes),
    // resolving the standard escapes we care about. Returns None if
    // the cursor is not on a `"`.
    //
    // Bytes are accumulated as raw UTF-8 and decoded once at the end:
    // a JSON string may carry multi-byte UTF-8 sequences directly (the
    // real .sections.json files do -- "es ésta" is stored as the
    // bytes 0xC3 0xA9, not an escape), so pushing each byte as its own
    // char would turn é into "Ã©". \uXXXX escapes are emitted as the
    // UTF-8 encoding of their codepoint.
    fn read_string(&mut self) -> Option<String> {
        self.skip_ws();
        if self.peek()? != b'"' {
            return None;
        }
        self.pos += 1;
        let mut out: Vec<u8> = Vec::new();
        while let Some(b) = self.bump() {
            match b {
                b'"' => return Some(String::from_utf8_lossy(&out).into_owned()),
                b'\\' => {
                    let esc = self.bump()?;
                    match esc {
                        b'"' => out.push(b'"'),
                        b'\\' => out.push(b'\\'),
                        b'/' => out.push(b'/'),
                        b'n' => out.push(b'\n'),
                        b't' => out.push(b'\t'),
                        b'r' => out.push(b'\r'),
                        b'b' => out.push(0x08),
                        b'f' => out.push(0x0C),
                        b'u' => {
                            // \uXXXX -- enough for the Spanish
                            // labels in the real files ("es ésta").
                            let hex = std::str::from_utf8(self.bytes.get(self.pos..self.pos + 4)?).ok()?;
                            let cp = u32::from_str_radix(hex, 16).ok()?;
                            self.pos += 4;
                            if let Some(ch) = char::from_u32(cp) {
                                let mut buf = [0u8; 4];
                                out.extend_from_slice(ch.encode_utf8(&mut buf).as_bytes());
                            }
                        }
                        _ => out.push(esc),
                    }
                }
                _ => out.push(b),
            }
        }
        None
    }

    // Read a JSON number (int or float, optional leading `-`). The
    // files store `at` as a float and `dwell` as either a float or
    // null, so this covers both.
    fn read_number(&mut self) -> Option<f64> {
        self.skip_ws();
        let start = self.pos;
        if let Some(b'-') = self.peek() {
            self.pos += 1;
        }
        while let Some(b) = self.peek() {
            if b.is_ascii_digit() || matches!(b, b'.' | b'e' | b'E' | b'+' | b'-') {
                self.pos += 1;
            } else {
                break;
            }
        }
        if self.pos == start || (self.pos == start + 1 && self.bytes.get(start) == Some(&b'-')) {
            return None;
        }
        std::str::from_utf8(self.bytes.get(start..self.pos)?)
            .ok()?
            .parse::<f64>()
            .ok()
    }

    // Skip one JSON value (object/array/string/number/keyword) at the
    // cursor. Used to step over values for keys we do not read.
    fn skip_value(&mut self) {
        self.skip_ws();
        match self.peek() {
            Some(b'"') => {
                _ = self.read_string();
            }
            Some(b'{') => self.skip_braced(b'{', b'}'),
            Some(b'[') => self.skip_braced(b'[', b']'),
            Some(b't') | Some(b'f') | Some(b'n') => {
                // true / false / null
                while let Some(b) = self.peek() {
                    if b.is_ascii_alphabetic() {
                        self.pos += 1;
                    } else {
                        break;
                    }
                }
            }
            Some(_) => {
                _ = self.read_number();
            }
            None => {}
        }
    }

    fn skip_braced(&mut self, open: u8, close: u8) {
        // Assumes cursor is on `open`.
        let mut depth = 0i32;
        while let Some(b) = self.bump() {
            if b == open {
                depth += 1;
            } else if b == close {
                depth -= 1;
                if depth == 0 {
                    return;
                }
            } else if b == b'"' {
                _ = self.read_string();
            }
        }
    }
}

/// Parse a `.sections.json` document (already loaded to a string)
/// into the timeline shape. Tolerates truncation: a partial file
/// yields whatever sections closed cleanly.
pub fn parse_sections_json(text: &str) -> ParsedSong {
    let mut raw = RawFile::default();
    let mut scan = JsonScan::new(text);

    // Top-level object.
    scan.skip_ws();
    if scan.peek() != Some(b'{') {
        return ParsedSong {
            song: String::new(),
            groups: build_groups(&[]),
            duration: 0.0,
        };
    }
    scan.pos += 1;

    loop {
        scan.skip_ws();
        match scan.peek() {
            None => break,
            Some(b'}') => {
                let _ = scan.bump();
                break;
            }
            Some(b',') => {
                scan.pos += 1;
                continue;
            }
            Some(b'"') => {
                let key = scan.read_string().unwrap_or_default();
                scan.skip_ws();
                if scan.peek() == Some(b':') {
                    scan.pos += 1;
                }
                match key.as_str() {
                    "song" => {
                        raw.song = scan.read_string();
                    }
                    "sections" => {
                        raw.sections = read_sections_array(&mut scan);
                    }
                    _ => {
                        scan.skip_value();
                    }
                }
            }
            _ => {
                scan.pos += 1;
            }
        }
    }

    parsed_song_from_raw(&raw)
}

fn read_sections_array(scan: &mut JsonScan<'_>) -> Vec<RawSection> {
    let mut out = Vec::new();
    scan.skip_ws();
    if scan.peek() != Some(b'[') {
        return out;
    }
    scan.pos += 1;
    loop {
        scan.skip_ws();
        match scan.peek() {
            None => return out,
            Some(b']') => {
                scan.pos += 1;
                return out;
            }
            Some(b',') => {
                scan.pos += 1;
                continue;
            }
            Some(b'{') => {
                if let Some(sec) = read_one_section(scan) {
                    out.push(sec);
                }
            }
            _ => {
                scan.pos += 1;
            }
        }
    }
}

fn read_one_section(scan: &mut JsonScan<'_>) -> Option<RawSection> {
    // Assumes cursor is on `{`.
    scan.skip_ws();
    if scan.peek()? != b'{' {
        return None;
    }
    scan.pos += 1;
    let mut label = None;
    let mut dwell: Option<f32> = None;
    let mut source = None;
    let mut at = None;
    loop {
        scan.skip_ws();
        match scan.peek() {
            None => return None,
            Some(b'}') => {
                scan.pos += 1;
                break;
            }
            Some(b',') => {
                scan.pos += 1;
                continue;
            }
            Some(b'"') => {
                let key = scan.read_string()?;
                scan.skip_ws();
                if scan.peek() == Some(b':') {
                    scan.pos += 1;
                }
                match key.as_str() {
                    "label" => label = scan.read_string(),
                    "source" => source = scan.read_string(),
                    "dwell" => {
                        scan.skip_ws();
                        match scan.peek() {
                            Some(b'n') => {
                                // null
                                while let Some(b) = scan.peek() {
                                    if b.is_ascii_alphabetic() {
                                        scan.pos += 1;
                                    } else {
                                        break;
                                    }
                                }
                                dwell = None;
                            }
                            _ => {
                                if let Some(n) = scan.read_number() {
                                    dwell = Some(n as f32);
                                }
                            }
                        }
                    }
                    "at" => {
                        if let Some(n) = scan.read_number() {
                            at = Some(n);
                        }
                    }
                    _ => scan.skip_value(),
                }
            }
            _ => {
                scan.pos += 1;
            }
        }
    }
    Some(RawSection {
        label,
        dwell,
        source,
        at,
    })
}

// ── raw -> timeline ──────────────────────────────────────────

fn parsed_song_from_raw(raw: &RawFile) -> ParsedSong {
    // Build a time-ordered list of (at, dwell, label, orbits) for
    // the sections that actually carry a timestamp. Sections without
    // an `at` cannot be placed on the timeline and are dropped -- a
    // bench run that did not finish will not have written them.
    let mut placed: Vec<(f64, Option<f32>, String, Vec<String>)> = Vec::new();
    for s in &raw.sections {
        let Some(at) = s.at else { continue };
        let label = s
            .label
            .clone()
            .unwrap_or_else(|| format!("section-{}", placed.len() + 1));
        let orbits = s
            .source
            .as_deref()
            .map(orbits_in_source)
            .unwrap_or_default();
        placed.push((at, s.dwell, label, orbits));
    }
    placed.sort_by(|a, b| a.0.partial_cmp(&b.0).unwrap_or(std::cmp::Ordering::Equal));

    let first_at = placed.first().map(|(at, _, _, _)| *at).unwrap_or(0.0);

    // Per-section start (seconds from song start) and duration.
    // Duration: explicit dwell if set, else the gap to the next
    // section, else the default for the final section.
    let mut timed: Vec<(f32, f32, String, Vec<String>)> = Vec::new();
    for (i, (at, dwell, label, orbits)) in placed.iter().enumerate() {
        let start = (*at - first_at) as f32;
        let duration = if let Some(d) = *dwell {
            d
        } else if let Some((next_at, _, _, _)) = placed.get(i + 1) {
            (*next_at - *at) as f32
        } else {
            DEFAULT_SECTION_DURATION
        };
        // Clamp negatives / zeros so a collapsed gap still shows a
        // visible block on the lane.
        let duration = duration.max(0.5);
        timed.push((start, duration, label.clone(), orbits.clone()));
    }

    let duration = timed
        .last()
        .map(|(start, dur, _, _)| start + dur)
        .unwrap_or(0.0);

    ParsedSong {
        song: raw.song.clone().unwrap_or_default(),
        groups: build_groups(&timed),
        duration,
    }
}

// Route the time-ordered sections into the three static groups and
// their orbit lanes. A lane is only emitted if at least one section
// routes to it; lanes within a group are ordered a1, a2, ..., b1, ...
fn build_groups(timed: &[(f32, f32, String, Vec<String>)]) -> Vec<ParsedGroup> {
    GROUPS
        .iter()
        .map(|(name, prefix)| {
            // Collect sections per orbit index.
            let mut lanes: Vec<(usize, Vec<ParsedSection>)> = Vec::new();
            for (start, dur, label, orbits) in timed {
                for orbit in orbits {
                    let Some(rest) = orbit.strip_prefix(*prefix) else {
                        continue;
                    };
                    let Ok(idx) = rest.parse::<usize>() else {
                        continue;
                    };
                    if idx == 0 || idx > MAX_ORBITS_PER_GROUP {
                        continue;
                    }
                    match lanes.iter_mut().find(|(i, _)| *i == idx) {
                        Some(slot) => slot.1.push(ParsedSection {
                            label: label.clone(),
                            start: *start,
                            duration: *dur,
                        }),
                        None => lanes.push((
                            idx,
                            vec![ParsedSection {
                                label: label.clone(),
                                start: *start,
                                duration: *dur,
                            }],
                        )),
                    }
                }
            }
            lanes.sort_by_key(|(i, _)| *i);
            let tracks = lanes
                .into_iter()
                .map(|(i, mut secs)| {
                    secs.sort_by(|a, b| {
                        a.start
                            .partial_cmp(&b.start)
                            .unwrap_or(std::cmp::Ordering::Equal)
                    });
                    ParsedTrack {
                        orbit: format!("{prefix}{i}"),
                        sections: secs,
                    }
                })
                .collect();
            ParsedGroup {
                name: (*name).to_string(),
                tracks,
            }
        })
        .collect()
}

// ── disk entry points ────────────────────────────────────────

/// The path the parser reads for a given song folder.
pub fn sections_path(song_dir: &Path) -> PathBuf {
    song_dir.join(".sections.json")
}

/// Parse `runs/<song>/.sections.json`. Returns an empty ParsedSong
/// (no groups, no sections) when the file is missing or unreadable
/// -- the dropdown lists every song folder, including the ones that
/// have not been benched yet.
pub fn parse_song_sections(song_dir: &Path) -> ParsedSong {
    let path = sections_path(song_dir);
    let Ok(text) = std::fs::read_to_string(&path) else {
        return ParsedSong {
            song: String::new(),
            groups: build_groups(&[]),
            duration: 0.0,
        };
    };
    parse_sections_json(&text)
}

// ── Slint model bridge ───────────────────────────────────────
// Convert the parsed timeline into the generated GroupData /
// TrackData / SectionData structs the SongTimeline component binds
// to. is-active / is-muted / is-soloed are read-only display fields
// here (the SONG view is read-only), so they default to active=true,
// muted/soloed=false -- matching the mock in ui/timeline.slint.

pub fn to_group_model(song: &ParsedSong) -> ModelRc<GroupData> {
    let groups: Vec<GroupData> = song
        .groups
        .iter()
        .map(|g| {
            let tracks: Vec<TrackData> = g
                .tracks
                .iter()
                .map(|t| {
                    let sections: Vec<SectionData> = t
                        .sections
                        .iter()
                        .map(|s| SectionData {
                            name: SharedString::from(s.label.as_str()),
                            start_time: s.start,
                            duration: s.duration,
                            is_active: true,
                        })
                        .collect();
                    TrackData {
                        name: SharedString::from(t.orbit.as_str()),
                        is_soloed: false,
                        is_muted: false,
                        sections: ModelRc::new(VecModel::from_slice(&sections)),
                    }
                })
                .collect();
            GroupData {
                name: SharedString::from(g.name.as_str()),
                // The accent is picked by group index on the Slint side
                // (Theme.group-beats / -leads / -ambients), matching the
                // convention in mute_model(); default here is overridden.
                accent: slint::Color::default(),
                tracks: ModelRc::new(VecModel::from_slice(&tracks)),
            }
        })
        .collect();
    ModelRc::new(VecModel::from_slice(&groups))
}

/// Song folder names under `runs/`, sorted alphabetically. Each is
/// a candidate for the dropdown. Folders without a `.sections.json`
/// are still listed -- the user can select them, and Apply will
/// show an empty timeline rather than failing.
pub fn list_song_folders(runs_dir: &Path) -> Vec<String> {
    let Ok(rd) = std::fs::read_dir(runs_dir) else {
        return Vec::new();
    };
    let mut out: Vec<String> = rd
        .flatten()
        .filter(|e| e.file_type().is_ok_and(|t| t.is_dir()))
        .map(|e| e.file_name().to_string_lossy().into_owned())
        .collect();
    out.sort();
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── orbit routing ────────────────────────────────────────

    #[test]
    fn routes_orbit_statements() {
        let src = "do\n  hush\n  l6 $ layer [...]\n  b1 $ slowcat [...]";
        let mut got = orbits_in_source(src);
        got.sort();
        assert_eq!(got, vec!["b1".to_string(), "l6".to_string()]);
    }

    #[test]
    fn ignores_dollar_in_expressions() {
        // `$` inside a pattern, not at statement start, must not route.
        let src = "do\n  s \"bd $ ~\"";
        assert!(orbits_in_source(src).is_empty());
    }

    #[test]
    fn dedups_repeated_orbit_in_one_section() {
        let src = "do\n  l3 $ ...\n  l3 $ ...";
        assert_eq!(orbits_in_source(src), vec!["l3".to_string()]);
    }

    #[test]
    fn accepts_a_b_l_prefixes_only() {
        let src = "do\n  a2 $ x\n  b4 $ y\n  l1 $ z\n  c1 $ w";
        let mut got = orbits_in_source(src);
        got.sort();
        assert_eq!(got, vec!["a2", "b4", "l1"]);
    }

    #[test]
    fn tolerates_spaces_before_dollar() {
        let src = "do\n  l3   $ x";
        assert_eq!(orbits_in_source(src), vec!["l3".to_string()]);
    }

    // ── full-file parsing ────────────────────────────────────

    fn ecdysis_like() -> &'static str {
        r#"{
            "song": "/home/endo/songs/05-ecdysis-108bpm.tidal",
            "floor_synths": 90,
            "sections": [
                { "label": ":ECDYSIS", "dwell": null,
                  "source": "do\n  l6 $ layer [density 0.25] $ stack [...]",
                  "line": 2, "at": 1000.0 },
                { "label": "section-2", "dwell": null,
                  "source": "do\n  l5 $ layer [stut 4 0.5 1]",
                  "line": 28, "at": 1005.0 },
                { "label": "es ésta", "dwell": null,
                  "source": "do -- es ésta\n  l4 $ every 4 (fast 2) $ layer [...]",
                  "line": 40, "at": 1010.0 },
                { "label": "mixed", "dwell": 8.0,
                  "source": "do\n  b1 $ slowcat [...]\n  l3 $ layer [...]\n  a1 $ ...",
                  "line": 53, "at": 1015.0 }
            ]
        }"#
    }

    #[test]
    fn parses_full_file_into_groups() {
        let song = parse_sections_json(ecdysis_like());
        assert_eq!(song.song, "/home/endo/songs/05-ecdysis-108bpm.tidal");
        // Three static groups, in order.
        assert_eq!(
            song.groups
                .iter()
                .map(|g| g.name.as_str())
                .collect::<Vec<_>>(),
            vec!["BEATS", "LEADS", "AMBIENTS"]
        );
        // BEATS got b1 from "mixed".
        let beats = &song.groups[0];
        assert_eq!(beats.tracks.len(), 1);
        assert_eq!(beats.tracks[0].orbit, "b1");
        // LEADS got l6/l5/l4 from the first three + l3 from mixed.
        let leads = &song.groups[1];
        let lead_names: Vec<&str> = leads.tracks.iter().map(|t| t.orbit.as_str()).collect();
        assert!(lead_names.contains(&"l3"));
        assert!(lead_names.contains(&"l4"));
        assert!(lead_names.contains(&"l5"));
        assert!(lead_names.contains(&"l6"));
        // AMBIENTS got a1 from "mixed".
        let ambients = &song.groups[2];
        assert_eq!(ambients.tracks[0].orbit, "a1");
    }

    #[test]
    fn start_times_are_offset_from_first_section() {
        let song = parse_sections_json(ecdysis_like());
        let leads = &song.groups[1];
        let l4 = leads
            .tracks
            .iter()
            .find(|t| t.orbit == "l4")
            .expect("l4 lane present");
        assert_eq!(l4.sections.len(), 1);
        // at=1010, first at=1000 -> start=10
        assert!((l4.sections[0].start - 10.0).abs() < 1e-3);
    }

    #[test]
    fn duration_uses_dwell_when_present() {
        let song = parse_sections_json(ecdysis_like());
        let beats = &song.groups[0];
        // "mixed" had dwell=8.0
        assert!((beats.tracks[0].sections[0].duration - 8.0).abs() < 1e-3);
    }

    #[test]
    fn duration_uses_gap_to_next_when_dwell_null() {
        let song = parse_sections_json(ecdysis_like());
        let leads = &song.groups[1];
        let l6 = leads
            .tracks
            .iter()
            .find(|t| t.orbit == "l6")
            .expect("l6 lane present");
        // :ECDYSIS at=1000, next section at=1005 -> 5s
        assert!((l6.sections[0].duration - 5.0).abs() < 1e-3);
        // start = 0
        assert!((l6.sections[0].start - 0.0).abs() < 1e-3);
    }

    #[test]
    fn sections_within_a_lane_are_time_ordered() {
        let song = parse_sections_json(ecdysis_like());
        let leads = &song.groups[1];
        let l3 = leads
            .tracks
            .iter()
            .find(|t| t.orbit == "l3")
            .expect("l3 lane present");
        // Only one section routed to l3 here, but still sorted.
        assert_eq!(l3.sections.len(), 1);
        assert!((l3.sections[0].start - 15.0).abs() < 1e-3);
    }

    #[test]
    fn unicode_label_survives() {
        let song = parse_sections_json(ecdysis_like());
        let leads = &song.groups[1];
        let l4 = leads
            .tracks
            .iter()
            .find(|t| t.orbit == "l4")
            .expect("l4 lane present");
        assert_eq!(l4.sections[0].label, "es ésta");
    }

    #[test]
    fn literal_utf8_label_survives() {
        // The real files store multi-byte UTF-8 directly (not as \u
        // escapes): "es ésta" is the bytes 65 73 20 e9 73 74 61 after
        // the JSON quotes. The reader must decode UTF-8, not push each
        // byte as its own char (which yields "Ã©").
        let text = r#"{
            "sections": [
                { "label": "literal ésta", "source": "do\n  l1 $ x", "at": 1000.0 }
            ]
        }"#;
        let song = parse_sections_json(text);
        let leads = &song.groups[1];
        assert_eq!(leads.tracks[0].sections[0].label, "literal ésta");
    }

    #[test]
    fn song_duration_is_last_section_end() {
        let song = parse_sections_json(ecdysis_like());
        // Last section at=1015, dwell=8 -> ends at 23.
        assert!((song.duration - 23.0).abs() < 1e-3);
    }

    // ── robustness ───────────────────────────────────────────

    #[test]
    fn missing_file_is_empty() {
        let song = parse_song_sections(Path::new("/nonexistent-hub-song-folder"));
        assert!(song.is_empty());
        assert_eq!(song.groups.len(), 3); // groups still defined, just empty
        assert_eq!(song.duration, 0.0);
    }

    #[test]
    fn empty_string_is_empty() {
        let song = parse_sections_json("");
        assert!(song.is_empty());
    }

    #[test]
    fn truncated_file_yields_what_closed() {
        // The first section object is complete; the second is cut mid-string.
        let truncated = r#"{
            "song": "/x.tidal",
            "sections": [
                { "label": "ok", "dwell": null, "source": "do\n  l1 $ x", "at": 1000.0 },
                { "label": "cut"#;
        let song = parse_sections_json(truncated);
        assert!(!song.is_empty());
        let leads = &song.groups[1];
        assert_eq!(leads.tracks.len(), 1);
        assert_eq!(leads.tracks[0].orbit, "l1");
    }

    #[test]
    fn section_without_at_is_dropped() {
        let text = r#"{
            "sections": [
                { "label": "placed", "source": "do\n  l1 $ x", "at": 1000.0 },
                { "label": "no-time", "source": "do\n  l2 $ y" }
            ]
        }"#;
        let song = parse_sections_json(text);
        let leads = &song.groups[1];
        let names: Vec<&str> = leads
            .tracks
            .iter()
            .flat_map(|t| t.sections.iter().map(|s| s.label.as_str()))
            .collect();
        assert!(names.contains(&"placed"));
        assert!(!names.contains(&"no-time"));
    }

    #[test]
    fn default_label_for_unnamed_section() {
        let text = r#"{
            "sections": [
                { "source": "do\n  l1 $ x", "at": 1000.0 }
            ]
        }"#;
        let song = parse_sections_json(text);
        let leads = &song.groups[1];
        assert_eq!(leads.tracks[0].sections[0].label, "section-1");
    }

    // ── disk listing ─────────────────────────────────────────

    #[test]
    fn list_song_folders_missing_dir_is_empty() {
        assert!(list_song_folders(Path::new("/nonexistent-runs-dir")).is_empty());
    }

    // ── real on-disk data ────────────────────────────────────
    // The actual ecdysis run: 43 sections, every one routed to at
    // least one orbit (verified in tools/orbitreport.py's domain).
    // This guards the parser against drift in the real schema and
    // confirms the orbit-routing regex holds on real Tidal sources.
    // Runs against runs/ecdysis/.sections.json; skipped (no panic)
    // if that file is not present on this machine.
    #[test]
    fn real_ecdysis_parses_into_all_three_groups() {
        let dir = std::path::Path::new(super::RUNS_DIR).join("ecdysis");
        let path = sections_path(&dir);
        let Ok(text) = std::fs::read_to_string(&path) else {
            return; // not benched here; nothing to assert
        };
        let song = parse_sections_json(&text);
        assert!(!song.is_empty(), "ecdysis should have sections");
        assert_eq!(song.groups.len(), 3);
        // Every group has at least one track lane -- the song uses
        // beats, leads, and ambients throughout.
        for g in &song.groups {
            assert!(!g.tracks.is_empty(), "{} has no tracks", g.name);
        }
        // BEATS / LEADS / AMBIENTS order, matching the static grid.
        assert_eq!(
            song.groups
                .iter()
                .map(|g| g.name.as_str())
                .collect::<Vec<_>>(),
            vec!["BEATS", "LEADS", "AMBIENTS"]
        );
        // Song duration is positive and bounded (the run is minutes,
        // not hours; 43 sections * ~5s cadence ≈ 215s).
        assert!(song.duration > 100.0 && song.duration < 10_000.0);
    }
}